spring:
  datasource:
    url: "jdbc:mysql://217.154.85.170:3306/AviDB"
    username: "avi"
    password: "J7h0kegGhK6E1uFJa8br"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false

server:
  address: 127.0.0.1
  port: 9898
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: aviboot
    key-store-type: PKCS12
    key-alias: aviboot

app:
  jwt:
    secret: x1sGcA3LSXEd+C7f5qWbYqExtPilMBJPGHnSRAAHdiFVZ8XojeE1VwiAT4MHMiKrr4HtPZxFeoOxooGZTtIApih7yX2TIkMIbfYFmW2ht5NRsw37tNFvR+gsvzIyzafQSf/J+Nk9hsVChKbeT2sRRYSPt0dgo8olBZud2ic73gI=
    expirationMs: 86400000  # 24 hours




# Optional Logging Config
# logging:
#   level:
#     root: OFF
